name: FocusFlow Release Builds

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build and package
        run: npm run package -- --publish never

      - name: Upload FocusFlow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: focusflow-${{ matrix.os }}
          path: |
            release/*.exe
            release/*.zip
            release/*.dmg
            release/*.AppImage
          if-no-files-found: warn

  publish:
    name: Publish release assets
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release
          merge-multiple: true

      - name: Upload FocusFlow assets to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*
          fail_on_unmatched_files: false
